//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classes()
        {
            this.Heroes = new HashSet<Hero>();
        }
    
        public int Id { get; set; }
        public string NomClasse { get; set; }
        public string Description { get; set; }
        public int StatsBaseStr { get; set; }
        public int StatsBaseDex { get; set; }
        public int StatsBaseInt { get; set; }
        public int StatsBaseVitalitê { get; set; }
        public int MondeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hero> Heroes { get; set; }
        public virtual Monde Monde { get; set; }
    }
}
