//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int Id { get; set; }
        public int Niveau { get; set; }
        public int Experience { get; set; }
        public string x { get; set; }
        public string y { get; set; }
        public int Argent { get; set; }
        public int StatsStr { get; set; }
        public int StatsDex { get; set; }
        public int StatsInt { get; set; }
        public int StatsVitalitê { get; set; }
        public string NomHero { get; set; }
        public bool EstConnectê { get; set; }
        public int InventaireHeroId { get; set; }
        public int MondeId { get; set; }
    
        public virtual Classes Class { get; set; }
        public virtual CompteJoueur CompteJoueur { get; set; }
        public virtual InventaireHero InventaireHero { get; set; }
        public virtual Monde Monde { get; set; }
    }
}
