//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HugoLandDbContainer : DbContext
    {
        public HugoLandDbContainer()
            : base("name=HugoLandDbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Hero> Heroes { get; set; }
        public virtual DbSet<CompteJoueur> CompteJoueurs { get; set; }
        public virtual DbSet<Monde> Mondes { get; set; }
        public virtual DbSet<ObjetMonde> ObjetMondes { get; set; }
        public virtual DbSet<InventaireHero> InventaireHeroes { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<EffetItem> EffetItems { get; set; }
        public virtual DbSet<Monstre> Monstres { get; set; }
    }
}
