//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoLandEditeur
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monstre
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int StatVitalitê { get; set; }
        public int StatDmgMin { get; set; }
        public int StatDmgMax { get; set; }
        public int MondeId { get; set; }
    
        public virtual Monde Monde { get; set; }
    }
}
